# Generated by Django 2.0.6 on 2019-05-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_name',
        ),
    ]
