# Generated by Django 2.2 on 2019-05-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_search', '0002_remove_image_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_loc',
            field=models.ImageField(upload_to='images/current/'),
        ),
    ]
